//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: AssemblyTitle("xUnit.net Specifications")]
[assembly: AssemblyDescription("BDD extensions for xUnit.net")]
[assembly: AssemblyProduct("xUnit.net Specifications")]
[assembly: AssemblyCopyright("Copyright © Arnold Zokas 2009")]
[assembly: ComVisible(false)]
[assembly: Guid("1344d0ac-5791-45bc-80aa-e66174717d50")]
[assembly: AssemblyVersion("0.1.050510.2")]
[assembly: AssemblyFileVersion("0.1.050510.2")]


